# Generated by Django 5.1.7 on 2025-03-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adolescente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('data_nascimento', models.DateField()),
                ('pg', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
