# Generated by Django 5.1.7 on 2025-03-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescente',
            name='genero_adolescente',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
