# Generated by Django 5.1.7 on 2025-03-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0002_adolescente_genero_adolescente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adolescente',
            old_name='genero_adolescente',
            new_name='genero',
        ),
    ]
