# Generated by Django 5.1.7 on 2025-04-15 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescentes', '0003_rename_genero_adolescente_adolescente_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='adolescente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('adolescente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adolescentes.adolescente')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adolescentes.diaevento')),
            ],
        ),
    ]
